/* SPDX-License-Identifier: GPL-2.0 OR BSD-3-Clause
   This file is automatically generated! */

#include "vmlinux.h"
#include <bpf/bpf_tracing.h>
#include <bpf/bpf_helpers.h>

#include "gotrace.h"

char LICENSE[] SEC("license") = "Dual BSD/GPL";

struct {
	__uint(type, BPF_MAP_TYPE_RINGBUF);
	__uint(max_entries, 167772160);
} rb SEC(".maps");




// Entry of main.getGoroutineID
SEC("uprobe///home/gzvv/Desktop/bp/simple_recursion/simple_recursion:main.getGoroutineID")
int BPF_UPROBE(main_getGoroutineID_entry) {

	u64 tgid_pid = bpf_get_current_pid_tgid();
	u32 pid = tgid_pid >> 32;
	u32 tgid = tgid_pid;

	struct basic_info *evt = {0};

	evt = bpf_ringbuf_reserve(&rb, sizeof(*evt), 0);
	if (!evt) {
		bpf_printk("ringbuffer not reserved");
		return 0;
	}

	evt->type = 0;
	evt->tgid = tgid;
	evt->pid = pid;
	evt->ts = bpf_ktime_get_ns();
	evt->func = 0;

	bpf_ringbuf_submit(evt, 0);
	
	bpf_printk("main.getGoroutineID entry");
	return 0;
}


// Exit of main.getGoroutineID with offset 0x172
SEC("uprobe///home/gzvv/Desktop/bp/simple_recursion/simple_recursion:main.getGoroutineID+0x172")
int BPF_UPROBE(main_getGoroutineID_leave_0)
{
	u64 tgid_pid = bpf_get_current_pid_tgid();
	u32 pid = tgid_pid >> 32;
	u32 tgid = tgid_pid;

	struct basic_info *evt = {0};

	evt = bpf_ringbuf_reserve(&rb, sizeof(*evt), 0);
	if (!evt) {
		bpf_printk("ringbuffer not reserved");
		return 0;
	}

	evt->type = 1;
	evt->tgid = tgid;
	evt->pid = pid;
	evt->ts = bpf_ktime_get_ns();
	evt->func = 0;

	bpf_ringbuf_submit(evt, 0);
	
	bpf_printk("main.getGoroutineID leave 0");
	return 0;
}

// Morestack of main.getGoroutineID
SEC("uprobe///home/gzvv/Desktop/bp/simple_recursion/simple_recursion:main.getGoroutineID+0x173")
int BPF_UPROBE(main_getGoroutineID_morestack) {

	u64 tgid_pid = bpf_get_current_pid_tgid();
	u32 pid = tgid_pid >> 32;
	u32 tgid = tgid_pid;

	struct basic_info *evt = {0};

	evt = bpf_ringbuf_reserve(&rb, sizeof(*evt), 0);
	if (!evt) {
		bpf_printk("ringbuffer not reserved");
		return 0;
	}

	evt->type = 2;
	evt->tgid = tgid;
	evt->pid = pid;
	evt->ts = bpf_ktime_get_ns();
	evt->func = 0;

	bpf_ringbuf_submit(evt, 0);
	
	bpf_printk("main.getGoroutineID morestack");
	return 0;
}


// Entry of main.recursiveFunction
SEC("uprobe///home/gzvv/Desktop/bp/simple_recursion/simple_recursion:main.recursiveFunction")
int BPF_UPROBE(main_recursiveFunction_entry) {

	u64 tgid_pid = bpf_get_current_pid_tgid();
	u32 pid = tgid_pid >> 32;
	u32 tgid = tgid_pid;

	struct basic_info *evt = {0};

	evt = bpf_ringbuf_reserve(&rb, sizeof(*evt), 0);
	if (!evt) {
		bpf_printk("ringbuffer not reserved");
		return 0;
	}

	evt->type = 0;
	evt->tgid = tgid;
	evt->pid = pid;
	evt->ts = bpf_ktime_get_ns();
	evt->func = 1;

	bpf_ringbuf_submit(evt, 0);
	
	bpf_printk("main.recursiveFunction entry");
	return 0;
}


// Exit of main.recursiveFunction with offset 0x78
SEC("uprobe///home/gzvv/Desktop/bp/simple_recursion/simple_recursion:main.recursiveFunction+0x78")
int BPF_UPROBE(main_recursiveFunction_leave_0)
{
	u64 tgid_pid = bpf_get_current_pid_tgid();
	u32 pid = tgid_pid >> 32;
	u32 tgid = tgid_pid;

	struct basic_info *evt = {0};

	evt = bpf_ringbuf_reserve(&rb, sizeof(*evt), 0);
	if (!evt) {
		bpf_printk("ringbuffer not reserved");
		return 0;
	}

	evt->type = 1;
	evt->tgid = tgid;
	evt->pid = pid;
	evt->ts = bpf_ktime_get_ns();
	evt->func = 1;

	bpf_ringbuf_submit(evt, 0);
	
	bpf_printk("main.recursiveFunction leave 0");
	return 0;
}

// Exit of main.recursiveFunction with offset 0x1ad
SEC("uprobe///home/gzvv/Desktop/bp/simple_recursion/simple_recursion:main.recursiveFunction+0x1ad")
int BPF_UPROBE(main_recursiveFunction_leave_1)
{
	u64 tgid_pid = bpf_get_current_pid_tgid();
	u32 pid = tgid_pid >> 32;
	u32 tgid = tgid_pid;

	struct basic_info *evt = {0};

	evt = bpf_ringbuf_reserve(&rb, sizeof(*evt), 0);
	if (!evt) {
		bpf_printk("ringbuffer not reserved");
		return 0;
	}

	evt->type = 1;
	evt->tgid = tgid;
	evt->pid = pid;
	evt->ts = bpf_ktime_get_ns();
	evt->func = 1;

	bpf_ringbuf_submit(evt, 0);
	
	bpf_printk("main.recursiveFunction leave 1");
	return 0;
}

// Morestack of main.recursiveFunction
SEC("uprobe///home/gzvv/Desktop/bp/simple_recursion/simple_recursion:main.recursiveFunction+0x1b3")
int BPF_UPROBE(main_recursiveFunction_morestack) {

	u64 tgid_pid = bpf_get_current_pid_tgid();
	u32 pid = tgid_pid >> 32;
	u32 tgid = tgid_pid;

	struct basic_info *evt = {0};

	evt = bpf_ringbuf_reserve(&rb, sizeof(*evt), 0);
	if (!evt) {
		bpf_printk("ringbuffer not reserved");
		return 0;
	}

	evt->type = 2;
	evt->tgid = tgid;
	evt->pid = pid;
	evt->ts = bpf_ktime_get_ns();
	evt->func = 1;

	bpf_ringbuf_submit(evt, 0);
	
	bpf_printk("main.recursiveFunction morestack");
	return 0;
}


// Entry of main.main
SEC("uprobe///home/gzvv/Desktop/bp/simple_recursion/simple_recursion:main.main")
int BPF_UPROBE(main_main_entry) {

	u64 tgid_pid = bpf_get_current_pid_tgid();
	u32 pid = tgid_pid >> 32;
	u32 tgid = tgid_pid;

	struct basic_info *evt = {0};

	evt = bpf_ringbuf_reserve(&rb, sizeof(*evt), 0);
	if (!evt) {
		bpf_printk("ringbuffer not reserved");
		return 0;
	}

	evt->type = 0;
	evt->tgid = tgid;
	evt->pid = pid;
	evt->ts = bpf_ktime_get_ns();
	evt->func = 2;

	bpf_ringbuf_submit(evt, 0);
	
	bpf_printk("main.main entry");
	return 0;
}


// Exit of main.main with offset 0xaa
SEC("uprobe///home/gzvv/Desktop/bp/simple_recursion/simple_recursion:main.main+0xaa")
int BPF_UPROBE(main_main_leave_0)
{
	u64 tgid_pid = bpf_get_current_pid_tgid();
	u32 pid = tgid_pid >> 32;
	u32 tgid = tgid_pid;

	struct basic_info *evt = {0};

	evt = bpf_ringbuf_reserve(&rb, sizeof(*evt), 0);
	if (!evt) {
		bpf_printk("ringbuffer not reserved");
		return 0;
	}

	evt->type = 1;
	evt->tgid = tgid;
	evt->pid = pid;
	evt->ts = bpf_ktime_get_ns();
	evt->func = 2;

	bpf_ringbuf_submit(evt, 0);
	
	bpf_printk("main.main leave 0");
	return 0;
}

// Morestack of main.main
SEC("uprobe///home/gzvv/Desktop/bp/simple_recursion/simple_recursion:main.main+0xab")
int BPF_UPROBE(main_main_morestack) {

	u64 tgid_pid = bpf_get_current_pid_tgid();
	u32 pid = tgid_pid >> 32;
	u32 tgid = tgid_pid;

	struct basic_info *evt = {0};

	evt = bpf_ringbuf_reserve(&rb, sizeof(*evt), 0);
	if (!evt) {
		bpf_printk("ringbuffer not reserved");
		return 0;
	}

	evt->type = 2;
	evt->tgid = tgid;
	evt->pid = pid;
	evt->ts = bpf_ktime_get_ns();
	evt->func = 2;

	bpf_ringbuf_submit(evt, 0);
	
	bpf_printk("main.main morestack");
	return 0;
}


