/* SPDX-License-Identifier: GPL-2.0 OR BSD-3-Clause
   This file is automatically generated! */

#include "vmlinux.h"
#include <bpf/bpf_tracing.h>
#include <bpf/bpf_helpers.h>

#include "gotrace.h"

char LICENSE[] SEC("license") = "Dual BSD/GPL";

#define GO_ID(x) ((x)->di)

struct {
	__uint(type, BPF_MAP_TYPE_RINGBUF);
	__uint(max_entries, {{ bpfring_size }});
} rb SEC(".maps");

{% for func_name, (offsets, morestack) in symbols.items() %}
{% set func_id = loop.index0 %}
// Entry of {{ func_name }}
SEC("uprobe//{{ path }}:{{ func_name }}")
int BPF_UPROBE({{ func_name|replace(".", "_") }}_entry) {

	u64 tgid_pid = bpf_get_current_pid_tgid();
	u32 pid = tgid_pid >> 32;
	u32 tgid = tgid_pid;

	struct task_struct *task = (struct task_struct *)bpf_get_current_task();
    uint64_t fsbase = 0;
    uint64_t gaddr = 0;
	uint64_t goid = 0;

	if (task) {
        bpf_probe_read(&fsbase, sizeof(fsbase), (void *)&task->thread.fsbase);
        if (fsbase) {
            // Assuming the gaddr is at offset -8 from fsbase 0xfffffffffffffff8
            bpf_probe_read(&gaddr, sizeof(gaddr), (void *)(fsbase - 8));
        }
		if(gaddr) {
			// Assuming the goid is at offset 152 from gaddr
			bpf_probe_read(&goid, sizeof(goid), (void *)(gaddr + 152));
		}
    }

	struct basic_info *evt = {0};

	evt = bpf_ringbuf_reserve(&rb, sizeof(*evt), 0);
	if (!evt) {
		bpf_printk("ringbuffer not reserved");
		return 0;
	}

	evt->type = 0;
	evt->morestack = 0;
	evt->tgid = tgid;
	evt->pid = pid;
	evt->goid = goid;
	evt->ts = bpf_ktime_get_ns();
	evt->func = {{ func_id }};

	bpf_ringbuf_submit(evt, 0);
	
	bpf_printk("{{ func_name }} entry");
	return 0;
}

{% for offset in offsets %}
// Exit of {{ func_name }} with offset {{ offset }}
SEC("uprobe//{{ path }}:{{ func_name }}+{{ offset }}")
int BPF_UPROBE({{ func_name|replace(".", "_") }}_leave_{{ loop.index0 }})
{
	u64 tgid_pid = bpf_get_current_pid_tgid();
	u32 pid = tgid_pid >> 32;
	u32 tgid = tgid_pid;

	struct task_struct *task = (struct task_struct *)bpf_get_current_task();
    uint64_t fsbase = 0;
    uint64_t gaddr = 0;
	uint64_t goid = 0;

	if (task) {
        bpf_probe_read(&fsbase, sizeof(fsbase), (void *)&task->thread.fsbase);
        if (fsbase) {
            // Assuming the gaddr is at offset -8 from fsbase 0xfffffffffffffff8
            bpf_probe_read(&gaddr, sizeof(gaddr), (void *)(fsbase - 8));
        }
		if(gaddr) {
			// Assuming the goid is at offset 152 from gaddr
			bpf_probe_read(&goid, sizeof(goid), (void *)(gaddr + 152));
		}
    }

	struct basic_info *evt = {0};

	evt = bpf_ringbuf_reserve(&rb, sizeof(*evt), 0);
	if (!evt) {
		bpf_printk("ringbuffer not reserved");
		return 0;
	}

	evt->type = 1;
	evt->morestack = 0;
	evt->tgid = tgid;
	evt->pid = pid;
	evt->goid = goid;
	evt->ts = bpf_ktime_get_ns();
	evt->func = {{ func_id }};

	bpf_ringbuf_submit(evt, 0);
	
	bpf_printk("{{ func_name }} leave {{ loop.index0 }}");
	return 0;
}
{% endfor %}
// Morestack of {{ func_name }}
SEC("uprobe//{{ path }}:{{ func_name }}+{{ morestack }}")
int BPF_UPROBE({{ func_name|replace(".", "_") }}_morestack) {

	u64 tgid_pid = bpf_get_current_pid_tgid();
	u32 pid = tgid_pid >> 32;
	u32 tgid = tgid_pid;

	struct task_struct *task = (struct task_struct *)bpf_get_current_task();
    uint64_t fsbase = 0;
    uint64_t gaddr = 0;
	uint64_t goid = 0;

	if (task) {
        bpf_probe_read(&fsbase, sizeof(fsbase), (void *)&task->thread.fsbase);
        if (fsbase) {
            // Assuming the gaddr is at offset -8 from fsbase 0xfffffffffffffff8
            bpf_probe_read(&gaddr, sizeof(gaddr), (void *)(fsbase - 8));
        }
		if(gaddr) {
			// Assuming the goid is at offset 152 (18*uint_64 + 2*uint32_t) from gaddr
			bpf_probe_read(&goid, sizeof(goid), (void *)(gaddr + 152));
		}
    }

	struct basic_info *evt = {0};

	evt = bpf_ringbuf_reserve(&rb, sizeof(*evt), 0);
	if (!evt) {
		bpf_printk("ringbuffer not reserved");
		return 0;
	}

	evt->type = 0;
	evt->morestack = 1;
	evt->tgid = tgid;
	evt->pid = pid;
	evt->goid = goid;
	evt->ts = bpf_ktime_get_ns();
	evt->func = {{ func_id }};

	bpf_ringbuf_submit(evt, 0);
	
	bpf_printk("{{ func_name }} morestack");
	return 0;
}
{% endfor %}


