/* SPDX-License-Identifier: GPL-2.0 OR BSD-3-Clause
   This file is automatically generated! */

#include "vmlinux.h"
#include <bpf/bpf_tracing.h>
#include <bpf/bpf_helpers.h>

#include "gotrace.h"

char LICENSE[] SEC("license") = "Dual BSD/GPL";

struct {
	__uint(type, BPF_MAP_TYPE_RINGBUF);
	__uint(max_entries, {{ bpfring_size }});
} rb SEC(".maps");


{% for func_name, (offsets, morestack) in symbols.items() %}
{% set func_id = loop.index0 %}
// Entry of {{ func_name }}
SEC("uprobe//{{ path }}:{{ func_name }}")
int BPF_UPROBE({{ func_name|replace(".", "_") }}_entry) {

	u64 tgid_pid = bpf_get_current_pid_tgid();
	u32 pid = tgid_pid >> 32;
	u32 tgid = tgid_pid;

	struct basic_info *evt = {0};

	evt = bpf_ringbuf_reserve(&rb, sizeof(*evt), 0);
	if (!evt) {
		bpf_printk("ringbuffer not reserved");
		return 0;
	}

	evt->type = 0;
	evt->tgid = tgid;
	evt->pid = pid;
	evt->ts = bpf_ktime_get_ns();
	evt->func = {{ func_id }};

	bpf_ringbuf_submit(evt, 0);
	
	bpf_printk("{{ func_name }} entry");
	return 0;
}

{% for offset in offsets %}
// Exit of {{ func_name }} with offset {{ offset }}
SEC("uprobe//{{ path }}:{{ func_name }}+{{ offset }}")
int BPF_UPROBE({{ func_name|replace(".", "_") }}_leave_{{ loop.index0 }})
{
	u64 tgid_pid = bpf_get_current_pid_tgid();
	u32 pid = tgid_pid >> 32;
	u32 tgid = tgid_pid;

	struct basic_info *evt = {0};

	evt = bpf_ringbuf_reserve(&rb, sizeof(*evt), 0);
	if (!evt) {
		bpf_printk("ringbuffer not reserved");
		return 0;
	}

	evt->type = 1;
	evt->tgid = tgid;
	evt->pid = pid;
	evt->ts = bpf_ktime_get_ns();
	evt->func = {{ func_id }};

	bpf_ringbuf_submit(evt, 0);
	
	bpf_printk("{{ func_name }} leave {{ loop.index0 }}");
	return 0;
}
{% endfor %}
// Morestack of {{ func_name }}
SEC("uprobe//{{ path }}:{{ func_name }}+{{ morestack }}")
int BPF_UPROBE({{ func_name|replace(".", "_") }}_morestack) {

	u64 tgid_pid = bpf_get_current_pid_tgid();
	u32 pid = tgid_pid >> 32;
	u32 tgid = tgid_pid;

	struct basic_info *evt = {0};

	evt = bpf_ringbuf_reserve(&rb, sizeof(*evt), 0);
	if (!evt) {
		bpf_printk("ringbuffer not reserved");
		return 0;
	}

	evt->type = 2;
	evt->tgid = tgid;
	evt->pid = pid;
	evt->ts = bpf_ktime_get_ns();
	evt->func = {{ func_id }};

	bpf_ringbuf_submit(evt, 0);
	
	bpf_printk("{{ func_name }} morestack");
	return 0;
}
{% endfor %}


